name: Github Pages Deloy
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create Node Environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: npm install
      - name: Deploy
        run: npm run deploy